# syntax=docker/dockerfile:1
# =============================================================================
# Multi-stage build for the Next.js "web" container (Node 22).
#   deps    -> install all dependencies (cached on package manifests)
#   build   -> compile the Next.js app (produces .next/standalone)
#   runtime -> minimal production image running the standalone server
# The same image also serves the one-shot `migrate` service (compose overrides
# the command); migrations need devDependencies (drizzle-kit), so the migrate
# command is run from a layer that still has them — see docker-compose.yml.
# =============================================================================

# ----------------------------------------------------------------------------
# Stage 1: deps — install node_modules (incl. dev deps for build & migrate)
# ----------------------------------------------------------------------------
FROM node:22-bookworm-slim AS deps
WORKDIR /app

# Copy only manifests first so this layer is cached unless deps change.
COPY package.json package-lock.json ./
# Deterministic, reproducible install from the lockfile.
RUN npm ci

# ----------------------------------------------------------------------------
# Stage 2: build — compile the Next.js application
# ----------------------------------------------------------------------------
FROM node:22-bookworm-slim AS build
WORKDIR /app

# Reuse the installed dependencies from the deps stage.
COPY --from=deps /app/node_modules ./node_modules
COPY . .

# next.config.ts sets output: "standalone"; this emits .next/standalone.
RUN npm run build

# ----------------------------------------------------------------------------
# Stage 3: runtime — minimal production image
# ----------------------------------------------------------------------------
FROM node:22-bookworm-slim AS runtime
WORKDIR /app

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1
ENV PORT=3000
ENV HOSTNAME=0.0.0.0

# Run as the unprivileged `node` user shipped with the official image.
USER node

# Standalone output bundles a minimal node_modules + server.js.
COPY --from=build --chown=node:node /app/.next/standalone ./
# Static assets and the public dir are not included in standalone output.
COPY --from=build --chown=node:node /app/.next/static ./.next/static
COPY --from=build --chown=node:node /app/public ./public

EXPOSE 3000

# server.js is the entrypoint generated by Next.js standalone output.
CMD ["node", "server.js"]
